export type ProductCategory = "Accessories" | "Beauty" | "Bags" | "Home";

export interface Product {
  id: number;
  name: string;
  category: ProductCategory;
  price: number;
  originalPrice: number;
  rating: number;
  discount: number;
  image: string;
}

export const CATEGORIES: Array<"All" | ProductCategory> = [
  "All",
  "Accessories",
  "Beauty",
  "Bags",
  "Home",
];

export const OFFER_SLIDES = [
  {
    id: 1,
    title: "Carlit x StarVille",
    tiers: [
      { points: 100, discount: "5%" },
      { points: 200, discount: "10%" },
      { points: 300, discount: "15%" },
      { points: 400, discount: "20%" },
    ],
    image: "/products/slider-carlit-starville.png",
  },
  {
    id: 2,
    title: "Carlit Earbuds",
    tiers: [
      { points: 100, discount: "5%" },
      { points: 200, discount: "10%" },
      { points: 300, discount: "15%" },
      { points: 400, discount: "20%" },
    ],
    image: "/products/slider-carlit-earbuds.png",
  },
  {
    id: 3,
    title: "Carlit x Gre Leaves",
    tiers: [
      { points: 100, discount: "5%" },
      { points: 200, discount: "10%" },
      { points: 300, discount: "15%" },
      { points: 400, discount: "20%" },
    ],
    image: "/products/slider-carlit-shampoo.png",
  },
  {
    id: 4,
    title: "Carlit Organic Bar",
    tiers: [
      { points: 100, discount: "5%" },
      { points: 200, discount: "10%" },
      { points: 300, discount: "15%" },
      { points: 400, discount: "20%" },
    ],
    image: "/products/slider-carlit-soap.png",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Neutrogena Pink Grapefruit",
    category: "Beauty",
    price: 437,
    originalPrice: 460,
    rating: 4.5,
    discount: 5,
    image: "/products/neutrogena-grapefruit.png",
  },
  {
    id: 2,
    name: "Nivea Men Face Wash",
    category: "Beauty",
    price: 285,
    originalPrice: 317,
    rating: 4.3,
    discount: 10,
    image: "/products/nivea-men-face-wash.png",
  },
  {
    id: 3,
    name: "The Organic Face Serum",
    category: "Beauty",
    price: 425,
    originalPrice: 472,
    rating: 4.8,
    discount: 10,
    image: "/products/organic-face-serum.png",
  },
  {
    id: 4,
    name: "Sophia's Tea Collection",
    category: "Home",
    price: 320,
    originalPrice: 356,
    rating: 4.6,
    discount: 10,
    image: "/products/sophias-tea.png",
  },
  {
    id: 5,
    name: "Brand Cosmetics Set",
    category: "Beauty",
    price: 640,
    originalPrice: 711,
    rating: 4.7,
    discount: 10,
    image: "/products/brand-cosmetics.png",
  },
  {
    id: 6,
    name: "Geo Leaves Hair Care",
    category: "Beauty",
    price: 295,
    originalPrice: 328,
    rating: 4.4,
    discount: 10,
    image: "/products/geo-leaves-hair-care.png",
  },
  {
    id: 7,
    name: "Gue Leaves Detox Shampoo",
    category: "Beauty",
    price: 245,
    originalPrice: 272,
    rating: 4.5,
    discount: 10,
    image: "/products/gue-leaves-shampoo.png",
  },
  {
    id: 8,
    name: "Professional Camera",
    category: "Accessories",
    price: 12500,
    originalPrice: 13125,
    rating: 4.9,
    discount: 5,
    image: "/products/professional-camera.png",
  },
  {
    id: 9,
    name: "Wireless Headphones",
    category: "Accessories",
    price: 890,
    originalPrice: 989,
    rating: 4.6,
    discount: 10,
    image: "/products/wireless-headphones.png",
  },
  {
    id: 10,
    name: "StarVille Facial Cleanser",
    category: "Beauty",
    price: 210,
    originalPrice: 233,
    rating: 4.3,
    discount: 10,
    image: "/products/slider-carlit-starville.png",
  },
  {
    id: 11,
    name: "Carlit Wireless Earbuds",
    category: "Accessories",
    price: 750,
    originalPrice: 833,
    rating: 4.5,
    discount: 10,
    image: "/products/slider-carlit-earbuds.png",
  },
  {
    id: 12,
    name: "Gre Leaves Detox Shampoo",
    category: "Beauty",
    price: 230,
    originalPrice: 256,
    rating: 4.4,
    discount: 10,
    image: "/products/slider-carlit-shampoo.png",
  },
  {
    id: 13,
    name: "Carlit Organic Bar",
    category: "Beauty",
    price: 95,
    originalPrice: 105,
    rating: 4.2,
    discount: 10,
    image: "/products/slider-carlit-soap.png",
  },
  {
    id: 14,
    name: "Neutrogena Daily Scrub",
    category: "Beauty",
    price: 198,
    originalPrice: 220,
    rating: 4.4,
    discount: 10,
    image: "/products/neutrogena-grapefruit.png",
  },
  {
    id: 15,
    name: "Nivea Deep Cleaning Wash",
    category: "Beauty",
    price: 175,
    originalPrice: 194,
    rating: 4.3,
    discount: 10,
    image: "/products/nivea-men-face-wash.png",
  },
  {
    id: 16,
    name: "Organic Revitalizing Serum",
    category: "Beauty",
    price: 380,
    originalPrice: 400,
    rating: 4.7,
    discount: 5,
    image: "/products/organic-face-serum.png",
  },
];
